# Generated by Django 5.1.3 on 2025-01-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_servicerequest_specimen_diagnosticreport'),
        ('emr', '0005_alter_availability_slot_size_in_minutes_and_more'),
    ]

    operations = [
    ]
