# Generated by Django 5.1.3 on 2025-01-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_merge_20250110_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='phase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
