# Generated by Django 5.1.3 on 2025-01-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_alter_patient_blood_group'),
        ('emr', '0007_servicerequest_phase'),
    ]

    operations = [
    ]
