# Generated by Django 5.1.1 on 2025-01-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0020_servicerequest_location_specimen_condition_and_more'),
        ('emr', '0061_rename_resource_schedulableuserresource_user_and_more'),
    ]

    operations = [
    ]
