# Generated by Django 5.1.1 on 2025-01-05 13:22

import care.emr.models.organization
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0063_diagnosticreport_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_request', to='emr.encounter'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='location',
            field=models.UUIDField(blank=True, null=True, verbose_name=care.emr.models.organization.Organization),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_request', to='emr.patient'),
        ),
    ]
