# Generated by Django 5.1.1 on 2025-01-05 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0064_alter_servicerequest_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreport',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_report', to='emr.encounter'),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_report', to='emr.patient'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimen', to='emr.patient'),
        ),
    ]
